name: Build an push to AWS

on:
    push:
        branches:
            - main


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '6.0'

            - name: Build projckt
              run: dotnet restore; dotnet publish -o site;

            - name: create zip package
              run: cd site; zip ../site.zip *;

            - name: Deploy toaws EB
              uses: einaregilsson/beanstalk-deploy@v21
              with: 
                aws_access_key:
                aws_secret_key:
                application_name:
                environment_name:
                version_label:
                region:
                deployment_package: site.zip

                
                